/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 起動確認
         * @description バックエンドが起動していれば `{ "status": "ok" }` を返す。DB の接続状態までは確認しない。
         */
        get: operations["AppController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * スポット一覧の取得
         * @description 登録されているスポットを返す。lat・lng・radius を指定すると、中心から radius メートル以内のスポットだけを、近い順に（distance つきで）返す。指定しない場合は、id の昇順で全件を返す。
         */
        get: operations["SpotsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/geocode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 座標から住所を取得
         * @description lat・lng の住所を、丁目までで返す。外部の Geocoding API を呼ぶ。結果は保存しない。
         */
        get: operations["GeocodeController_reverse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StatusResponseDto: {
            /**
             * @description 起動していれば常に "ok"
             * @example ok
             */
            status: string;
        };
        SpotResponseDto: {
            /**
             * @description スポット ID（bigint のため文字列で返す）
             * @example 1
             */
            id: string;
            /**
             * @description スポット名
             * @example 東京タワー
             */
            name: string;
            /**
             * @description カテゴリ（観光名所、公園、寺院など）
             * @example 観光名所
             */
            category: string;
            /**
             * @description 住所。未登録の場合は null
             * @example 東京都港区
             */
            address: string | null;
            /**
             * @description 緯度（WGS84）
             * @example 35.658581
             */
            lat: number;
            /**
             * @description 経度（WGS84）
             * @example 139.745433
             */
            lng: number;
            /**
             * @description 中心からの距離（メートル）。lat / lng / radius で絞り込んだときだけ返す
             * @example 1234.5
             */
            distance?: number;
        };
        ReverseAddressResponseDto: {
            /**
             * @description 座標の住所（丁目まで。番地・建物名・国名・郵便番号は含まない）。海の上など住所がない場所は null
             * @example 東京都千代田区丸の内１丁目
             */
            address: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 起動している */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponseDto"];
                };
            };
        };
    };
    SpotsController_findAll: {
        parameters: {
            query?: {
                /** @description 中心の緯度（WGS84）。lng と radius とセットで指定する */
                lat?: number;
                /** @description 中心の経度（WGS84）。lat と radius とセットで指定する */
                lng?: number;
                /** @description 中心からの距離（メートル）。0 より大きく 1000000 以下。lat と lng とセットで指定する */
                radius?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スポットの配列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotResponseDto"][];
                };
            };
            /** @description lat・lng・radius の一部だけの指定、または範囲外の値 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GeocodeController_reverse: {
        parameters: {
            query: {
                /** @description 緯度（WGS84） */
                lat: number;
                /** @description 経度（WGS84） */
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReverseAddressResponseDto"];
                };
            };
            /** @description lat・lng が、数値でない、または範囲外 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 外部の Geocoding API が失敗した */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description サーバー用の API キーが設定されていない */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
