/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 起動確認
         * @description バックエンドが起動していれば `{ "status": "ok" }` を返す。DB の接続状態までは確認しない。
         */
        get: operations["AppController_getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * スポット一覧の取得
         * @description 登録されているすべてのスポットを、id の昇順で返す。絞り込みやページングは未対応（常に全件）。
         */
        get: operations["SpotsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StatusResponseDto: {
            /**
             * @description 起動していれば常に "ok"
             * @example ok
             */
            status: string;
        };
        SpotResponseDto: {
            /**
             * @description スポット ID（bigint のため文字列で返す）
             * @example 1
             */
            id: string;
            /**
             * @description スポット名
             * @example 東京タワー
             */
            name: string;
            /**
             * @description カテゴリ（観光名所、公園、寺院など）
             * @example 観光名所
             */
            category: string;
            /**
             * @description 住所。未登録の場合は null
             * @example 東京都港区
             */
            address: string | null;
            /**
             * @description 緯度（WGS84）
             * @example 35.658581
             */
            lat: number;
            /**
             * @description 経度（WGS84）
             * @example 139.745433
             */
            lng: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 起動している */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponseDto"];
                };
            };
        };
    };
    SpotsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description スポットの配列 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpotResponseDto"][];
                };
            };
        };
    };
}
